services:
  front:
    image: dev-phonebook-frontend
    build:
      context: ./frontend/ # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    container_name: dev-phonebook-frontend # This will name the container hello-front-dev
    ports:
      - 3000:3000
  server:
    image: dev-phonebook-backend # names the image
    build:
      context: ./backend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./backend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    container_name: dev-phonebook-backend # This will name the container hello-backend-dev
    env_file:
      - ./backend/.env
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - front # wait for the frontend container to be started
      - server